# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e609ad8c6848c05e4481ba5666814ecc271dde563447e0905bed149e70c33864fef06791f82f67122789807e37994f4670ce9b15d2579ca060ae6873d1d1b9ec

test:
  secret_key_base: f7c1e12a4c40fc9042f0ee8743ac7a9860dea446ec5c9e1927695b12473e5779d4cfc3f6d5098066db5a1c69f353be1e88100a7a1a3a38af1291dea90a2c54b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
